"""add worker_state

Revision ID: e63211df19e8
Revises: a1b2c3d4e5f6
Create Date: 2026-07-19 00:30:44.620156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e63211df19e8'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate_limit_limit', sa.Integer(), nullable=False),
    sa.Column('rate_limit_remaining', sa.Integer(), nullable=True),
    sa.Column('backing_off', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('worker_state')
    # ### end Alembic commands ###
